### ISSUE TITLE
The plugin does not load

### ISSUE THREAD

**Issue by yuanshengaoshou114** [NotThorny/MobWave#10]
Use the latest 3.6grasscutter, as well as the latest plugins
java.lang.NoSuchMethodError: emu.grasscutter.game.dungeons.challenge.trigger.KillMonsterTrigger: method 'void <init>()' not found
        at thorny.grasscutters.MobWave.commands.MobWaveCommand.<init>(MobWaveCommand.java:38)
        at thorny.grasscutters.MobWave.MobWave.onEnable(MobWave.java:27)
        at emu.grasscutter.plugin.PluginManager.lambda$enablePlugins$2(PluginManager.java:205)
        at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
        at emu.grasscutter.plugin.PluginManager.enablePlugins(PluginManager.java:201)

**Comment by yuanshengaoshou114** [comment]
Use grasscutter is
https://github.com/YuukiPS/Grasscutters-Original

**Comment by NotThorny** [comment]
The Grasscutter you're using has a reworked data and challenge system, so the plugin may not work quite right, but I have updated it to load properly and it should hopefully work well enough.

[MobWave.zip](https://github.com/NotThorny/MobWave/files/11437246/MobWave.zip)
