### ISSUE TITLE
MobWave plugin not enabling 

### ISSUE THREAD

**Issue by MarkSemaan** [NotThorny/MobWave#4]
I got this when starting a server.
```
java.lang.NoClassDefFoundError: emu/grasscutter/command/CommandHelpers
        at thorny.grasscutters.MobWave.commands.MobWaveCommand.<clinit>(MobWaveCommand.java:78)
        at thorny.grasscutters.MobWave.MobWave.onEnable(MobWave.java:30)
        at emu.grasscutter.plugin.PluginManager.lambda$enablePlugins$2(PluginManager.java:202)
        at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
        at emu.grasscutter.plugin.PluginManager.enablePlugins(PluginManager.java:199)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:160)
Caused by: java.lang.ClassNotFoundException: emu.grasscutter.command.CommandHelpers
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 6 common frames omitted
```

**Comment by NotThorny** [comment]
You should not be seeing this error with a release jar, but I have seen it if you build the jar yourself with errors (usually import issues / 'emu' cannot be resolved) which is what looks to be the case.

I have tested with Grasscutter 1.3.2, 1.4.0, and 1.4.1 and it is working without issues on each. If you don't _need_ to build it yourself I'd recommend using the [latest release jar from releases](https://github.com/NotThorny/MobWave/releases) instead.
