### ISSUE TITLE
3.3bug

### ISSUE THREAD

**Issue by yuanshengaoshou114** [NotThorny/MobWave#7]
jar is https://github.com/YuukiPS/DockerGS
05:09:33 <ERROR:PluginManager> Failed to enable plugin: MobWave
java.lang.NullPointerException: null
        at java.base/java.io.Reader.<init>(Reader.java:168)
        at java.base/java.io.InputStreamReader.<init>(InputStreamReader.java:76)
        at thorny.grasscutters.MobWave.commands.MobWaveCommand.readFile(MobWaveCommand.java:92)
        at thorny.grasscutters.MobWave.MobWave.onEnable(MobWave.java:37)
        at emu.grasscutter.plugin.PluginManager.lambda$enablePlugins$2(PluginManager.java:216)
        at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
        at emu.grasscutter.plugin.PluginManager.enablePlugins(PluginManager.java:213)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:196)

**Comment by NotThorny** [comment]
Only since this does not actually appear to be an error caused by 3.3, but rather a modified jar perhaps, I've gone ahead and updated the error message and info just in case. The plugin won't totally fail to load in the case of a missing monsters.json, but it will only have one mob of each type in the available spawns.

You can try again with the updated release of [Mobwave 1.2.1](https://github.com/NotThorny/MobWave/releases/tag/1.2.1).

If this is an issue caused specifically by using 3.3, then it won't be updated/fixed/supported until Grasscutter officially updates to 3.3, as that is what this is built on and for.

**Comment by yuanshengaoshou114** [comment]
> Only since this does not actually appear to be an error caused by 3.3, but rather a modified jar perhaps, I've gone ahead and updated the error message and info just in case. The plugin won't totally fail to load in the case of a missing monsters.json, but it will only have one mob of each type in the available spawns.
> 
> You can try again with the updated release of [Mobwave 1.2.1](https://github.com/NotThorny/MobWave/releases/tag/1.2.1).
> 
> If this is an issue caused specifically by using 3.3, then it won't be updated/fixed/supported until Grasscutter officially updates to 3.3, as that is what this is built on and for.

Use https://github.com/YuukiPS/DockerGS
Failed to load file monsters.json, using minimal fallback.
java.lang.NullPointerException: null
        at java.base/java.io.Reader.<init>(Reader.java:168)
        at java.base/java.io.InputStreamReader.<init>(InputStreamReader.java:76)
        at thorny.grasscutters.MobWave.commands.MobWaveCommand.readFile(MobWaveCommand.java:92)
        at thorny.grasscutters.MobWave.MobWave.onEnable(MobWave.java:34)
        at emu.grasscutter.plugin.PluginManager.lambda$enablePlugins$2(PluginManager.java:218)
        at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
        at emu.grasscutter.plugin.PluginManager.enablePlugins(PluginManager.java:215)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:196)

**Comment by yuanshengaoshou114** [comment]
> Only since this does not actually appear to be an error caused by 3.3, but rather a modified jar perhaps, I've gone ahead and updated the error message and info just in case. The plugin won't totally fail to load in the case of a missing monsters.json, but it will only have one mob of each type in the available spawns.
> 
> You can try again with the updated release of [Mobwave 1.2.1](https://github.com/NotThorny/MobWave/releases/tag/1.2.1).
> 
> If this is an issue caused specifically by using 3.3, then it won't be updated/fixed/supported until Grasscutter officially updates to 3.3, as that is what this is built on and for.

The mw start is normal, but the mw stop will generate many errors

**Comment by NotThorny** [comment]
Though I'm not exactly sure why the reader is failing, you can try again with this version built on the docker jar. If this one has the same issues then I can change the monster lists to not use the reader as a workaround for docker specifically.
[MobWave.zip](https://github.com/NotThorny/MobWave/files/10306818/MobWave.zip)

**Comment by yuanshengaoshou114** [comment]
> Though I'm not exactly sure why the reader is failing, you can try again with this version built on the docker jar. If this one has the same issues then I can change the monster lists to not use the reader as a workaround for docker specifically. [MobWave.zip](https://github.com/NotThorny/MobWave/files/10306818/MobWave.zip)

20:23:33 <ERROR:MobWaveCommand> [MobWave] Failed to load file monsters.json, using minimal fallback.
java.lang.NullPointerException: null
        at java.base/java.io.Reader.<init>(Reader.java:168)
        at java.base/java.io.InputStreamReader.<init>(InputStreamReader.java:76)
        at thorny.grasscutters.MobWave.commands.MobWaveCommand.readFile(MobWaveCommand.java:92)
        at thorny.grasscutters.MobWave.MobWave.onEnable(MobWave.java:34)
        at emu.grasscutter.plugin.PluginManager.lambda$enablePlugins$2(PluginManager.java:218)
        at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
        at emu.grasscutter.plugin.PluginManager.enablePlugins(PluginManager.java:215)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:196)

**Comment by NotThorny** [comment]
I went ahead and rewrote it to not use IO at all, and also fixed the entity removal issue from `mw stop`. Give this a try and let me know if there are any problems.
[MobWave.zip](https://github.com/NotThorny/MobWave/files/10311049/MobWave.zip)

**Comment by yuanshengaoshou114** [comment]
> I went ahead and rewrote it to not use IO at all, and also fixed the entity removal issue from `mw stop`. Give this a try and let me know if there are any problems. [MobWave.zip](https://github.com/NotThorny/MobWave/files/10311049/MobWave.zip)

11:10:36 <ERROR:CommandMap> Error Command at:
java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "emu.grasscutter.game.player.Player.getScene()" because "targetPlayer" is null
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:205)
        at emu.grasscutter.command.CommandMap.invoke(CommandMap.java:348)
        at emu.grasscutter.Grasscutter.startConsole(Grasscutter.java:341)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:202)
Caused by: java.lang.NullPointerException: Cannot invoke "emu.grasscutter.game.player.Player.getScene()" because "targetPlayer" is null
        at thorny.grasscutters.AttackModifier.commands.AttackModifierCommand.execute(AttackModifierCommand.java:44)
        at emu.grasscutter.command.CommandMap.lambda$invoke$0(CommandMap.java:343)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by NotThorny** [comment]
Looks like that was due to an unfortunate mistake with AttackModifier where the target requirement was missing, leading to that null pointer if no target was specified. I've updated the target requirement so you'll get the proper usage message if sending the command from cmd with no target.
[AttackModifier.zip](https://github.com/NotThorny/MobWave/files/10312536/AttackModifier.zip)
